import type { TProduct } from '../@types/coffee'

export const data: TProduct[] = [
  {
    variant: 'arabe',
    labels: ['especial'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    quantity: 1,
  },
  {
    variant: 'cafe-com-leite',
    labels: ['tradicional', 'com leite'],
    description: 'Café expresso misturado com leite vaporizado',
    price: 8.5,
    quantity: 1,
  },
  {
    variant: 'capuccino',
    labels: ['tradicional', 'com leite'],
    description: 'Café expresso com espuma de leite e canela',
    price: 10.0,
    quantity: 1,
  },
  {
    variant: 'chocolate-quente',
    labels: ['especial', 'com leite'],
    description: 'Delicioso chocolate quente cremoso',
    price: 12.0,
    quantity: 1,
  },
  {
    variant: 'cubano',
    labels: ['especial', 'alcoólico', 'gelado'],
    description: 'Café gelado com rum, creme de leite e hortelã',
    price: 11.5,
    quantity: 1,
  },
  {
    variant: 'expresso-americano',
    labels: ['tradicional'],
    description: 'Expresso diluído, suave e aromático',
    price: 7.5,
    quantity: 1,
  },
  {
    variant: 'expresso-cremoso',
    labels: ['tradicional'],
    description: 'Expresso tradicional mais encorpado com creme',
    price: 8.0,
    quantity: 1,
  },
  {
    variant: 'expresso-gelado',
    labels: ['tradicional', 'gelado'],
    description: 'Expresso servido gelado, refrescante',
    price: 9.0,
    quantity: 1,
  },
  {
    variant: 'expresso-tradicional',
    labels: ['tradicional'],
    description: 'Expresso forte, encorpado e clássico',
    price: 7.0,
    quantity: 1,
  },
  {
    variant: 'havaiano',
    labels: ['especial'],
    description: 'Café com leite de coco e especiarias tropicais',
    price: 11.0,
    quantity: 1,
  },
  {
    variant: 'irlandes',
    labels: ['especial', 'alcoólico'],
    description: 'Café com uísque irlandês e chantilly',
    price: 12.5,
    quantity: 1,
  },
  {
    variant: 'latte',
    labels: ['tradicional', 'com leite'],
    description: 'Café expresso com bastante leite vaporizado',
    price: 9.0,
    quantity: 1,
  },
  {
    variant: 'macchiato',
    labels: ['tradicional', 'com leite'],
    description: 'Expresso com uma pequena quantidade de leite',
    price: 8.5,
    quantity: 1,
  },
  {
    variant: 'mocaccino',
    labels: ['tradicional', 'com leite'],
    description: 'Café com chocolate e leite vaporizado',
    price: 10.5,
    quantity: 1,
  },
]
